-- ============================================================================
--  Cluevoyance: database baseline (shared accounts, Phase 1)
-- ============================================================================
--  The first migration this project has ever had. It declares the two content
--  tables the live game already uses (so the project rebuilds from git), and
--  adds the shared-account layer:
--
--    accounts            one row per Cluevoyance account; global_user_id is the
--                        WorkOS user id (the cross-game link), NOT a key for
--                        gameplay data. Written only by ensure_account().
--    cluevoyance_uid()   THE ACCOUNT BOUNDARY. Every policy and RPC that means
--                        "the caller" uses it instead of auth.uid(). An auth
--                        user without an accounts row is a guest, everywhere.
--    plays               one row per finished official puzzle per account
--                        (win or loss). Stats are derived from it on the
--                        client; nothing is stored twice.
--    admins              which accounts may write official content.
--
--  Modelled on Rainbow Categories' launch baseline (puzzle-connect-daily,
--  supabase/migrations/0001_rainbow_baseline.sql, "the account layer"), with
--  everything Rainbow needs for server-side guests left out: Cluevoyance
--  guests exist only in their own browser.
--
--  Rules kept from Rainbow:
--   * global_user_id is copied from auth.identities on the server, never from
--     a client value or user_metadata.
--   * An account's current email is read from its custom:platform identity
--     (account_email()); auth.users.email is only a fallback. Email is
--     metadata, never identity.
--   * Every table: REVOKE ALL from PUBLIC/anon/authenticated, then exactly the
--     intended DML. Every function: REVOKE, then GRANT by role.
--   * Outcomes are rows ("ok" / "not_platform_linked" / ...), not exceptions.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- A. CONTENT (already live). Declared EXACTLY as the hosted project has them
--    (read-only inventory of 2026-10-04: identity ids, text dates, created_at,
--    theme; wordbank keyed by an identity id with a unique word), so a blank
--    project rebuilds from git and the hosted project sees no-ops. The access
--    rules in section F DO apply there (decision D3).
-- ----------------------------------------------------------------------------
create table if not exists public.puzzles (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  date        text,            -- ISO yyyy-mm-dd as text (the live shape); plays copy it as a date
  title       text,
  author      text,
  difficulty  text,
  status      text,
  clues       jsonb,
  cards       jsonb,
  solution    jsonb,
  theme       text
);

create table if not exists public.wordbank (
  id    bigint generated always as identity primary key,
  word  text not null unique
);

-- ----------------------------------------------------------------------------
-- B. THE LOCAL ACCOUNT
-- ----------------------------------------------------------------------------
create table public.accounts (
  user_id         uuid primary key references auth.users(id) on delete cascade,
  global_user_id  text not null,
  created_at      timestamptz not null default now(),
  last_seen_at    timestamptz not null default now(),
  -- Guest losses only ever existed as a counter in the browser (no puzzle id),
  -- so "Add my progress" carries them over as a count. Shown in Played / Win % / X.
  imported_losses integer not null default 0 check (imported_losses >= 0),
  constraint accounts_global_user_id_key    unique (global_user_id),
  constraint accounts_global_user_id_format check (global_user_id ~ '^user_[0-9A-Za-z]{10,64}$')
);
comment on table  public.accounts is 'A Cluevoyance account. An auth user is a Cluevoyance account only when it has a row here; the only writer is ensure_account().';
comment on column public.accounts.global_user_id is 'The shared identity provider''s user id (user_...). The cross-game link and the reserved join key for future entitlements. Never a key for gameplay data.';

alter table public.accounts enable row level security;   -- no policies: reachable only through RPCs

-- The account boundary.
create function public.cluevoyance_uid() returns uuid
language sql stable security definer set search_path = public as $$
  select a.user_id
    from public.accounts a
   where a.user_id = auth.uid()
$$;
comment on function public.cluevoyance_uid() is 'The caller''s account id, or NULL when the caller is a guest or an auth user that is not a Cluevoyance account. Use this, never auth.uid(), in policies and RPCs.';

-- The ONE source of an account's current email (Rainbow smoke case S6: the
-- provider identity is refreshed on every sign-in, auth.users.email is not).
create function public.account_email(_user_id uuid) returns text
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select nullif(btrim(i.identity_data ->> 'email'), '')
       from public.accounts a
       join auth.identities i on i.user_id = a.user_id
      where a.user_id = _user_id
        and i.provider = 'custom:platform'
      order by i.created_at
      limit 1),
    (select u.email::text
       from public.accounts a
       join auth.users u on u.id = a.user_id
      where a.user_id = _user_id)
  )
$$;

-- Create or refresh the account behind the current session.
create function public.ensure_account()
returns table(outcome text, user_id uuid, global_user_id text, email text, created_at timestamptz, imported_losses integer)
language plpgsql security definer set search_path = public as $$
#variable_conflict use_column
declare
  _uid uuid := auth.uid();
  _gid text;
begin
  if _uid is null then
    return query select 'not_signed_in'::text, null::uuid, null::text, null::text, null::timestamptz, null::integer;
    return;
  end if;

  -- The link is read from GoTrue's identity table, never from the client.
  select i.provider_id
    into _gid
    from auth.identities i
   where i.user_id = _uid
     and i.provider = 'custom:platform'
   order by i.created_at
   limit 1;

  if _gid is null then
    -- An auth user that did not come through the shared sign-in (a dashboard
    -- or test user, a stray signup). Not, and never becomes, an account.
    return query select 'not_platform_linked'::text, null::uuid, null::text, null::text, null::timestamptz, null::integer;
    return;
  end if;

  insert into public.accounts (user_id, global_user_id)
  values (_uid, _gid)
  on conflict (user_id) do update
    set last_seen_at = now();

  return query
    select 'ok'::text, a.user_id, a.global_user_id, public.account_email(a.user_id), a.created_at, a.imported_losses
      from public.accounts a
     where a.user_id = _uid;
end;
$$;

create function public.my_account()
returns table(user_id uuid, global_user_id text, email text, created_at timestamptz, imported_losses integer)
language sql stable security definer set search_path = public as $$
  select a.user_id, a.global_user_id, public.account_email(a.user_id), a.created_at, a.imported_losses
    from public.accounts a
   where a.user_id = auth.uid()
$$;

create function public.ping() returns boolean
language sql stable set search_path = public as $$ select true $$;

-- ----------------------------------------------------------------------------
-- C. ADMINS (decision D3: minimal, database-enforced content writes)
-- ----------------------------------------------------------------------------
create table public.admins (
  user_id     uuid primary key references public.accounts(user_id) on delete cascade,
  granted_at  timestamptz not null default now()
);
comment on table public.admins is 'Accounts allowed to write official content. Granted by the owner in SQL: insert into public.admins (user_id) select user_id from public.accounts where global_user_id = ''user_...'';';
alter table public.admins enable row level security;

create function public.is_cluevoyance_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins ad where ad.user_id = public.cluevoyance_uid())
$$;

-- ----------------------------------------------------------------------------
-- D. PLAY HISTORY: the first server-side player data Cluevoyance has had.
-- ----------------------------------------------------------------------------
create table public.plays (
  user_id      uuid        not null references public.accounts(user_id) on delete cascade,
  puzzle_id    bigint      not null references public.puzzles(id) on delete cascade,
  puzzle_date  date        not null,      -- the puzzle's own date; streaks use this, not wall-clock time
  solved       boolean     not null,
  lives_used   smallint    not null check (lives_used between 0 and 3),
  difficulty   text        not null check (difficulty in ('easy', 'standard', 'expert', 'hardcore')),
  finished_at  timestamptz not null default now(),
  source       text        not null default 'play' check (source in ('play', 'import')),
  primary key (user_id, puzzle_id)
);
comment on table public.plays is 'One row per finished official puzzle per account (win or loss). A solved row is never downgraded. Stats are derived from these rows.';
create index plays_user_date_idx on public.plays (user_id, puzzle_date);

alter table public.plays enable row level security;
create policy plays_read_own on public.plays
  for select to authenticated
  using (user_id = public.cluevoyance_uid());

-- Upsert one finished puzzle. Shared by record_play and import_plays.
create function public.upsert_play(
  _uid uuid, _puzzle_id bigint, _solved boolean, _lives_used int, _difficulty text,
  _finished_at timestamptz, _source text
) returns text
language plpgsql security definer set search_path = public as $$
declare
  _date date;
begin
  -- puzzles.date is text on the live project; a malformed value counts as unknown
  begin
    select nullif(btrim(p.date), '')::date into _date from public.puzzles p where p.id = _puzzle_id;
  exception when others then
    _date := null;
  end;
  if _date is null then
    return 'unknown_puzzle';
  end if;
  if _solved is null or _lives_used is null or _lives_used < 0 or _lives_used > 3
     or _difficulty is null or _difficulty not in ('easy', 'standard', 'expert', 'hardcore') then
    return 'invalid';
  end if;

  insert into public.plays (user_id, puzzle_id, puzzle_date, solved, lives_used, difficulty, finished_at, source)
  values (_uid, _puzzle_id, _date, _solved, _lives_used, _difficulty, coalesce(_finished_at, now()), _source)
  on conflict (user_id, puzzle_id) do update
    set solved      = public.plays.solved or excluded.solved,
        -- a win keeps its own lives/difficulty; a loss may be upgraded by a later win
        lives_used  = case when public.plays.solved then public.plays.lives_used  else excluded.lives_used  end,
        difficulty  = case when public.plays.solved then public.plays.difficulty  else excluded.difficulty  end,
        finished_at = case when public.plays.solved then public.plays.finished_at else excluded.finished_at end,
        source      = case when public.plays.solved then public.plays.source      else excluded.source      end;
  return 'ok';
end;
$$;

-- Record a puzzle the signed-in account just finished.
create function public.record_play(_puzzle_id bigint, _solved boolean, _lives_used int, _difficulty text)
returns table(outcome text)
language plpgsql security definer set search_path = public as $$
declare
  _uid uuid := public.cluevoyance_uid();
begin
  if _uid is null then
    return query select 'not_signed_in'::text;
    return;
  end if;
  return query select public.upsert_play(_uid, _puzzle_id, _solved, _lives_used, _difficulty, now(), 'play');
end;
$$;

-- Import this browser's guest history, once, when the player chooses
-- "Add my progress". Elements: {puzzle_id, solved, lives_used, difficulty,
-- finished_at?} are the guest's wins. _losses is the guest's loss count (the
-- browser only ever kept losses as a counter, so they carry over as a count,
-- never as fabricated per-puzzle rows). Unknown puzzles and malformed elements
-- are skipped and counted; an existing solved row is never overwritten, so
-- repeating the wins changes nothing. The client sends the loss count once
-- (it clears the guest counters afterwards).
create function public.import_plays(_plays jsonb, _losses int default 0)
returns table(outcome text, imported int, skipped int)
language plpgsql security definer set search_path = public as $$
declare
  _uid uuid := public.cluevoyance_uid();
  _el jsonb;
  _res text;
  _imported int := 0;
  _skipped int := 0;
  _finished timestamptz;
begin
  if _uid is null then
    return query select 'not_signed_in'::text, 0, 0;
    return;
  end if;
  if _plays is null or jsonb_typeof(_plays) <> 'array' then
    return query select 'invalid'::text, 0, 0;
    return;
  end if;
  if jsonb_array_length(_plays) > 5000 or coalesce(_losses, 0) > 100000 then
    return query select 'too_many'::text, 0, 0;
    return;
  end if;

  if coalesce(_losses, 0) > 0 then
    update public.accounts set imported_losses = imported_losses + _losses where user_id = _uid;
  end if;

  for _el in select * from jsonb_array_elements(_plays) loop
    begin
      _finished := nullif(_el ->> 'finished_at', '')::timestamptz;
    exception when others then
      _finished := null;
    end;
    begin
      _res := public.upsert_play(
        _uid,
        (_el ->> 'puzzle_id')::bigint,
        (_el ->> 'solved')::boolean,
        (_el ->> 'lives_used')::int,
        _el ->> 'difficulty',
        _finished,
        'import');
    exception when others then
      _res := 'invalid';
    end;
    if _res = 'ok' then _imported := _imported + 1; else _skipped := _skipped + 1; end if;
  end loop;

  return query select 'ok'::text, _imported, _skipped;
end;
$$;

-- ----------------------------------------------------------------------------
-- E. DELETION
-- ----------------------------------------------------------------------------
create function public.delete_local_account(_user_id uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  if _user_id is null then
    return;
  end if;
  -- Cluevoyance keeps no site-wide aggregates, so personal rows are simply
  -- deleted (plays and admins also cascade from accounts).
  delete from public.plays    where user_id = _user_id;
  delete from public.admins   where user_id = _user_id;
  delete from public.accounts where user_id = _user_id;
  -- GoTrue's own cascades remove identities, sessions and refresh tokens.
  delete from auth.users where id = _user_id;
end;
$$;

create function public.delete_my_account() returns boolean
language plpgsql security definer set search_path = public as $$
declare
  _uid uuid := public.cluevoyance_uid();
begin
  if _uid is null then
    return false;
  end if;
  perform public.delete_local_account(_uid);
  return true;
end;
$$;

-- ----------------------------------------------------------------------------
-- F. CONTENT ACCESS RULES (decision D3)
--    Reading stays open to everyone, as today. Writing needs an admin account,
--    enforced here, not in the UI.
-- ----------------------------------------------------------------------------
alter table public.puzzles  enable row level security;
alter table public.wordbank enable row level security;

-- The live project's beta-era policies let anon do everything; they are
-- replaced by the rules below (no-ops on a blank project).
drop policy if exists "Anyone can read puzzles"     on public.puzzles;
drop policy if exists "Anyone can insert puzzles"   on public.puzzles;
drop policy if exists "Anyone can update puzzles"   on public.puzzles;
drop policy if exists "Anyone can delete puzzles"   on public.puzzles;
drop policy if exists "Anyone can read wordbank"    on public.wordbank;
drop policy if exists "Anyone can insert wordbank"  on public.wordbank;
drop policy if exists "Anyone can update wordbank"  on public.wordbank;
drop policy if exists "Anyone can delete wordbank"  on public.wordbank;

create policy puzzles_read_all      on public.puzzles  for select to anon, authenticated using (true);
create policy puzzles_admin_insert  on public.puzzles  for insert to authenticated with check (public.is_cluevoyance_admin());
create policy puzzles_admin_update  on public.puzzles  for update to authenticated using (public.is_cluevoyance_admin()) with check (public.is_cluevoyance_admin());
create policy puzzles_admin_delete  on public.puzzles  for delete to authenticated using (public.is_cluevoyance_admin());

create policy wordbank_read_all     on public.wordbank for select to anon, authenticated using (true);
create policy wordbank_admin_insert on public.wordbank for insert to authenticated with check (public.is_cluevoyance_admin());
create policy wordbank_admin_update on public.wordbank for update to authenticated using (public.is_cluevoyance_admin()) with check (public.is_cluevoyance_admin());
create policy wordbank_admin_delete on public.wordbank for delete to authenticated using (public.is_cluevoyance_admin());

-- ----------------------------------------------------------------------------
-- G. GRANTS: revoke everything, then grant by intent.
-- ----------------------------------------------------------------------------
revoke all on table public.puzzles, public.wordbank, public.accounts, public.admins, public.plays
  from public, anon, authenticated;

grant select                         on table public.puzzles, public.wordbank to anon, authenticated;
grant insert, update, delete         on table public.puzzles, public.wordbank to authenticated;   -- RLS: admins only
grant select                         on table public.plays                    to authenticated;   -- RLS: own rows
grant all on table public.puzzles, public.wordbank, public.accounts, public.admins, public.plays to service_role;

revoke all on function public.cluevoyance_uid()                                              from public, anon, authenticated;
revoke all on function public.account_email(uuid)                                            from public, anon, authenticated;
revoke all on function public.ensure_account()                                               from public, anon, authenticated;
revoke all on function public.my_account()                                                   from public, anon, authenticated;
revoke all on function public.ping()                                                         from public, anon, authenticated;
revoke all on function public.is_cluevoyance_admin()                                         from public, anon, authenticated;
revoke all on function public.upsert_play(uuid, bigint, boolean, int, text, timestamptz, text) from public, anon, authenticated;
revoke all on function public.record_play(bigint, boolean, int, text)                        from public, anon, authenticated;
revoke all on function public.import_plays(jsonb, int)                                       from public, anon, authenticated;
revoke all on function public.delete_local_account(uuid)                                     from public, anon, authenticated;
revoke all on function public.delete_my_account()                                            from public, anon, authenticated;

grant execute on function public.cluevoyance_uid()                       to anon, authenticated, service_role;
grant execute on function public.ping()                                  to anon, authenticated, service_role;
grant execute on function public.is_cluevoyance_admin()                  to anon, authenticated, service_role;
grant execute on function public.ensure_account()                        to authenticated, service_role;
grant execute on function public.my_account()                            to authenticated, service_role;
grant execute on function public.record_play(bigint, boolean, int, text) to authenticated, service_role;
grant execute on function public.import_plays(jsonb, int)                to authenticated, service_role;
grant execute on function public.delete_my_account()                     to authenticated, service_role;
grant execute on function public.account_email(uuid)                     to service_role;
grant execute on function public.upsert_play(uuid, bigint, boolean, int, text, timestamptz, text) to service_role;
grant execute on function public.delete_local_account(uuid)              to service_role;
